# Generated by Django 3.1 on 2023-04-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpage',
            name='client_id',
            field=models.IntegerField(unique=True),
        ),
    ]
